spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncodeing=utf-8
    username: root
    password: root

mybatis:
  type-aliases-package: com.blog.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    #指定 MyBatis 所用日志的具体实现，未指定时将自动查找
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 允许插入空值
    jdbc-type-for-null: null

pagehelper:
  #helper-dialect：配置使用哪种数据库语言，不配置的话pageHelper也会自动检测
  helperDialect: mysql
  # 分页合理化 默认不开启的
  reasonable: true
#支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  supportMethodsArguments: true

comment.avatar: /images/avatar.webp